x-web-configs:
  &webapi-defaults
  depends_on:
    - keycloak
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_HTTP_PORTS=8080
    - ASPNETCORE_HTTPS_PORTS=8081

    - OPENID_AUTHORITY=${OPENID_AUTHORITY}
    - OPENID_AUDIENCE=${OPENID_AUDIENCE}
  ports:
    - "8080"
    - "8081"
  volumes:
    - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  networks:
    - local_network

services:
  fiap.filecut.gestaoapi:
    container_name: filecut-gestao-api
    <<: *webapi-defaults

  fiap.filecut.uploadapi:
    container_name: filecut-upload-api
    <<: *webapi-defaults

  fiap.filecut.processamentoapi:
    container_name: filecut-processamento-api
    <<: *webapi-defaults

  keycloak:
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
  db_network:

volumes:
  keycloak_data:  